name: Startup Test

on:
  pull_request:
    paths:
      - 'deploy-plugin.sh'
      - 'server.properties'
      - 'data/ops.json'
      - 'setup.sh'
      - 'docker-compose.yml'
      - 'test/startup.sh'
      - '.github/workflows/startup-test.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python --version
          python3 -m pip install mcstatus
      - name: startup test
        run: ./test/startup.sh
